// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpBwsqtHMBfGZDf2SYr0KXXchz3vuSsPI',
    appId: '1:394290777611:web:24359c7487bcc1b6ab410e',
    messagingSenderId: '394290777611',
    projectId: 'fadly-auth',
    authDomain: 'fadly-auth.firebaseapp.com',
    storageBucket: 'fadly-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5ROdsAyjCP7X-UUzqWrCev6gkEIpRwA',
    appId: '1:394290777611:android:064f70a285954d60ab410e',
    messagingSenderId: '394290777611',
    projectId: 'fadly-auth',
    storageBucket: 'fadly-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPS_l2PowUhwO5gX9-9XQhfyQ3b4216_w',
    appId: '1:394290777611:ios:c5b86379ea7c741bab410e',
    messagingSenderId: '394290777611',
    projectId: 'fadly-auth',
    storageBucket: 'fadly-auth.appspot.com',
    iosBundleId: 'com.example.sanberappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPS_l2PowUhwO5gX9-9XQhfyQ3b4216_w',
    appId: '1:394290777611:ios:b7d0934026488fbfab410e',
    messagingSenderId: '394290777611',
    projectId: 'fadly-auth',
    storageBucket: 'fadly-auth.appspot.com',
    iosBundleId: 'com.example.sanberappflutter.RunnerTests',
  );
}
