// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwWXJkgY_l8uOJ_qlLI28GjEyhFvlLX8',
    appId: '1:1035592666332:web:3336dd640cc7836eae3819',
    messagingSenderId: '1035592666332',
    projectId: 'fadlyprojekapp',
    authDomain: 'fadlyprojekapp.firebaseapp.com',
    storageBucket: 'fadlyprojekapp.appspot.com',
    measurementId: 'G-NXZCCHF89J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBufW1EWjCAUbmNAO7Noq7FK9sFEyqn9KU',
    appId: '1:1035592666332:android:3439f3419ee26fa1ae3819',
    messagingSenderId: '1035592666332',
    projectId: 'fadlyprojekapp',
    storageBucket: 'fadlyprojekapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdcZCQBWgDquLj7RPDCcTNy2TItSWGtKk',
    appId: '1:1035592666332:ios:9398ab1976d5f66cae3819',
    messagingSenderId: '1035592666332',
    projectId: 'fadlyprojekapp',
    storageBucket: 'fadlyprojekapp.appspot.com',
    iosBundleId: 'com.example.fadlyprojekapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdcZCQBWgDquLj7RPDCcTNy2TItSWGtKk',
    appId: '1:1035592666332:ios:9461d8a7ccc7c021ae3819',
    messagingSenderId: '1035592666332',
    projectId: 'fadlyprojekapp',
    storageBucket: 'fadlyprojekapp.appspot.com',
    iosBundleId: 'com.example.fadlyprojekapp.RunnerTests',
  );
}
